on:
  workflow_call:
    inputs:
      REMOTE_URL:
        required: false
        type: string
        default: ${{ atomgit.repositoryurl }}
      pr_id:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.number }}
      IMAGE_FLAG:
        required: true
        type: string
        description: "Full SWR image URL, e.g. swr.<region>.<org>/mindx_arm:tag"
      TARGET_BRANCH:
        required: false
        type: string
        default: ${{ atomgit.event.pull_request.base.ref }}
      runs_on_arch:
        required: true
        type: string
        description: "x86 or arm"
      servicename:
        required: false
        type: string
        default: $(echo "${{ atomgit.repository }}" | cut -d '/' -f 2)
      DEFAULT_BRANCH:
        required: false
        type: string
        default: "develop"

jobs:
  JOB_compile:
    name: JOB_compile
    select: selected_by_default
    runs-on: [ self-hosted, "${{ inputs.runs_on_arch }}", cpu=32 ]
    container:
      image: ${{ inputs.IMAGE_FLAG }}
      options: --user root
    steps:
      - name: clone repo and merge PR
        run: |
          set -x
          servicename=$(echo "${{ atomgit.repository }}" | cut -d '/' -f 2)
          git clone --single-branch -b ${{ inputs.TARGET_BRANCH }} ${{ inputs.REMOTE_URL }} ${{ inputs.servicename }}
          cd ${{ inputs.servicename }}

          git fetch origin +refs/merge-requests/${{ inputs.pr_id }}/head:pr_${{ inputs.pr_id }}
          git reset --hard "origin/${{ inputs.TARGET_BRANCH }}"
          git checkout -b new_${{ inputs.TARGET_BRANCH }}
          git config --global user.name AtlasAccount
          git config --global user.email AtlasAccount@noreply.gitcode.com
          git merge --no-edit pr_${{ inputs.pr_id }}
          git diff-tree -r --name-only --no-commit-id origin/${{ inputs.TARGET_BRANCH }} HEAD > ${ATOMGIT_WORKSPACE}/change.txt
          cat ${ATOMGIT_WORKSPACE}/change.txt

          if [ "${{ inputs.TARGET_BRANCH }}" != "${{ inputs.DEFAULT_BRANCH }}" ]; then
              mkdir -p .gitcode/workflows
              git clone --single-branch --depth 1 -b ${{ inputs.DEFAULT_BRANCH }} ${{ inputs.REMOTE_URL }} ${ATOMGIT_WORKSPACE}/tempdir
              cp -fr ${ATOMGIT_WORKSPACE}/tempdir/.gitcode/workflows/scripts .gitcode/workflows/ 2>/dev/null || true
              cp -fr ${ATOMGIT_WORKSPACE}/tempdir/.gitcode/workflows/config .gitcode/workflows/ 2>/dev/null || true
              rm -fr ${ATOMGIT_WORKSPACE}/tempdir
          fi

      - name: prepare_dependency
        run: |
          set -e
          echo "ATOMGIT_WORKSPACE=${ATOMGIT_WORKSPACE}"
          echo "servicename=${{ inputs.servicename }}"
          mkdir -p ${ATOMGIT_WORKSPACE}/opensource
          cd ${ATOMGIT_WORKSPACE}/opensource
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/test_mxrec/opensource/huaweicloud-sdk-c-obs-3.23.9.zip
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/pybind11-2.10.3.zip
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/torchrec-release-v1.1.0.zip
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/torchrec-release-v1.2.0.zip
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/json-3.9.1.tar.gz
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/googletest-1.13.0.zip
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/spdlog-1.12.0.zip
          wget --no-check-certificate https://mindcluster.obs.cn-north-4.myhuaweicloud.com/blueImageDependency/emock-master.zip

      - name: compile
        run: |
          set -e
          echo "ATOMGIT_WORKSPACE=${ATOMGIT_WORKSPACE}"
          # echo '查看pytorch版本'
          # export LD_LIBRARY_PATH=/usr/local/python3.11.0/lib/:$LD_LIBRARY_PATH
          # export PATH=/usr/local/python3.11.0/bin:$PATH
          # python3 -m pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu
          # python3 -m pip show torch
          # echo '查看pytorch版本2'
          # python3 -c "import torch; print('PyTorch Version:', torch.__version__); print('Bind CUDA Version:', torch.version.cuda if hasattr(torch.version, 'cuda') else 'None'); print('File Path:', torch.__file__)"
          file_path='change.txt'
          if grep -q "training/torch_rec_v1/" "${ATOMGIT_WORKSPACE}/$file_path"; then
              cd ${ATOMGIT_WORKSPACE}
              bash +x ${ATOMGIT_WORKSPACE}/${{ inputs.servicename }}/.gitcode/workflows/scripts/ut_torch_rec_execute.sh ${{ inputs.servicename }}
          fi
